<?php

namespace Drupal\arhangel\Controller;

use Drupal\Core\Controller\ControllerBase;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Drupal\arhangel\HeroArticleService;

/**
 * This is our controller.
 */
class HeroController extends ControllerBase {

  private $articleHeroService;

  public static function create(ContainerInterface $container) {
    return new static(
      $container->get('arhangel.hero_articles')
    );
//    return parent::create($container); // TODO: Change the autogenerated stub
  }

  public function __construct(HeroArticleService $articleHeroService) {
    $this->articleHeroService = $articleHeroService;
  }

  public function heroList () {
    $heroes = [
//      'name' => 'Thor',
//      'name' => 'Wolverine',
//      'name' => 'Phoenix'
//    ];
      "Thor", "Wolverine", "Phoenix", "Batman", "Superman", "Spider-Man", "Wonder Woman" ];

    return [
      '#theme' => 'hero_list',
      '#items' => $heroes,
      '#title' => $this->t('Our wonderful heroes list'),
    ];
  }
}
